### ISSUE TITLE
Fix bug for deleting user input 

### ISSUE THREAD

**Issue by 04banshee** [cheddarmonk/super-duper-hepta-journey#11]
Currently hard coded to delete only Sally's input information.

**Comment by cheddarmonk** [comment]
@04banshee Unmerged changed. Need to remerge changes.

**Comment by cheddarmonk** [comment]
After Fields were updated, Bug was replicated. The main HTML was not calling the proper function. A line-by-line analysis showed that the ID references from HTML to the JS event listeners were missing. Replaced the references and the code runs correctly.
